#!/usr/bin/python3
from myclasses import Hero, Weapon, Monster

sword = Weapon("Sword", 5)
hammer = Weapon("Hammer", 100)
hero1 = Hero("Hero 1")
hero2 = Hero("Hero 2")
monster = Monster()

Hero.glob()

hero1.equip_weapon(hammer)
hero2.equip_weapon(hammer)
hero1.equip_weapon(hammer)
hero1.attack(monster)
monster.attack(hero1)
hero1.attack(monster)
monster.attack(hero1)
hero1.attack(monster)
monster.attack(hero1)
hero1.attack(monster)
monster.attack(hero1)
Hero.glob()
'''
hero1.attack(hero2)
hero2.attack(hero1)
hero1.attack(hero2)
hero2.attack(hero1)
hero1.attack(hero2)
hero2.attack(hero1)
Hero.glob()
hero1.equip_weapon(hammer)
Hero.glob()
hero1.attack(hero2)
hero1.attack(hero2)
hero1.attack(hero2)
Hero.glob()
hero1.attack(hero2)
hero2.attack(hero1)
hero1.attack(hero2)
hero2.attack(hero1)
hero1.attack(hero2)
hero2.attack(hero1)
hero1.attack(hero2)
hero2.attack(hero1)
hero1.attack(hero2)
hero2.attack(hero1)
hero1.attack(hero2)
hero2.attack(hero1)
hero1.attack(hero2)
hero2.attack(hero1)
hero1.attack(hero2)
hero2.attack(hero1)
hero1.attack(hero2)
hero2.attack(hero1)
Hero.glob()
'''